In [1]:
5 + 6

ans =  11


In [2]:
eye(5)

ans =

Diagonal Matrix

   1   0   0   0   0
   0   1   0   0   0
   0   0   1   0   0
   0   0   0   1   0
   0   0   0   0   1



In [3]:
pi

ans =  3.1416


In [5]:
A = [1 2; 3 4; 5 6]

A =

   1   2
   3   4
   5   6



In [1]:
B = [10 11; 12 13; 14 15]

B =

   10   11
   12   13
   14   15



In [2]:
C = [1 1; 2 2]

C =

   1   1
   2   2



In [6]:
A * C

ans =

    5    5
   11   11
   17   17



In [7]:
v=[1 2 3]

v =

   1   2   3



In [8]:
1 ./ v

ans =

   1.00000   0.50000   0.33333



In [9]:
1 ./ A

ans =

   1.00000   0.50000
   0.33333   0.25000
   0.20000   0.16667



In [10]:
log(v)

ans =

   0.00000   0.69315   1.09861



In [11]:
exp(v)

ans =

    2.7183    7.3891   20.0855



In [12]:
abs(v)

ans =

   1   2   3



In [13]:
-v

ans =

  -1  -2  -3



In [14]:
v + ones(length(v),1)

ans =

   2   3   4
   2   3   4
   2   3   4



In [15]:
ones(length(v),1)

ans =

   1
   1
   1



In [16]:
A

A =

   1   2
   3   4
   5   6



In [17]:
A'

ans =

   1   3   5
   2   4   6



In [18]:
a = [1 15 2 0.5]

a =

    1.00000   15.00000    2.00000    0.50000



In [19]:
max(a)

ans =  15


In [20]:
[val,indx] = max(a)

val =  15
indx =  2


In [21]:
max(A)

ans =

   5   6



In [22]:
[val,indx] = max(A)

val =

   5   6

indx =

   3   3



In [23]:
a < 3

ans =

   1   0   1   1



In [24]:
find(a < 3)

ans =

   1   3   4



In [27]:
A = magic(3)

A =

   8   1   6
   3   5   7
   4   9   2



In [28]:
[r, c] = find(A > 6)

r =

   1
   3
   2

c =

   1
   2
   3



In [29]:
A(2,3)

ans =  7


In [30]:
sum(a)

ans =  18.500


In [31]:
prod(a)

ans =  15


In [32]:
floor(a)

ans =

    1   15    2    0



In [33]:
ceil(a)

ans =

    1   15    2    1



In [34]:
A = rand(3)

A =

   0.79937   0.72326   0.68391
   0.47791   0.81508   0.96635
   0.76899   0.72973   0.11968



In [35]:
B = rand(3)

B =

   0.2341854   0.7271975   0.6296614
   0.5525589   0.6654899   0.7634758
   0.5487493   0.8657387   0.0038676



In [36]:
max(A,B)

ans =

   0.79937   0.72720   0.68391
   0.55256   0.81508   0.96635
   0.76899   0.86574   0.11968



In [40]:
max(A,[],1)

ans =

   0.79937   0.81508   0.96635



In [41]:
max(A,[],2)

ans =

   0.79937
   0.96635
   0.76899

